#pragma once

enum class EDriver{
	CarlosSainz,
	DaniilKvyat,
	DanielRicciardo,
	FernandoAlonso,
	FelipeMassa,
	KimiRaikkonen = 6,
	LewisHamilton,
	MaxVerstappen = 9,
	NicoHulkenberg,
	KevinMagnussen,
	RomainGrosjean,
	SebastianVettel,
	SergioPerez,
	ValtteriBottas,
	EstebanOcon = 17,
	LanceStroll = 19,
	ArronBarnes,
	MartinGiles,
	AlexMurray,
	LucasRoth,
	IgorCorreia,
	SophieLevasseur,
	JonasSchiffer,
	AlainForest,
	JayLetourneau,
	EstoSaari,
	YasarAtiyeh,
	CallistoCalabresi,
	NaotaIzum,
	HowardClarke,
	WilheimKaufmann,
	MarieLaursen,
	FlavioNieves,
	PeterBelousov,
	KlimekMichalski,
	SantiagoMoreno,
	BenjaminCoppens,
	NoahVisser,
	GertWaldmuller,
	JulianQuesada,
	DanielJones,
	ArtemMarkelov,
	TadasukeMakino,
	SeanGelael,
	NyckDeVries,
	JackAitken,
	GeorgeRussell,
	MaximilianGünther,
	NireiFukuzumi,
	LucaGhiotto,
	LandoNorris,
	SergioSetteCamara,
	LouisDeletraz,
	AntonioFuoco,
	CharlesLeclerc,
	PierreGasly,
	AlexanderAlbon = 62,
	NicholasLatifi,
	DorianBoccolacci,
	NikoKari,
	RobertoMerhi,
	ArjunMaini,
	AlessioLorandi,
	RubenMeijer,
	RashidNair,
	JackTremblay,
	DevonButler,
	LukasWeber,
	AntonioGiovinazzi,
	RobertKubica,
	AlainProst,
	AyrtonSenna,
	NobuharuMatsushita,
	NikitaMazepin,
	GuanyaZhou,
	MickSchumacher,
	CallumIlott,
	JuanManuelCorrea,
	JordanKing,
	MahaveerRaghunathan,
	TatianaCalderon,
	AnthoineHubert,
	GuilianoAlesi,
	RalphBoschung,
	MichaelSchumacher,
	DanTicktum,
	MarcusArmstrong,
	ChristianLundgaard,
	YukiTsunoda,
	JehanDaruvala,
	GulhermeSamaia,
	PedroPiquet,
	FelipeDrugovich,
	RobertSchwartzman,
	RoyNissany,
	MarinoSato,
	AidanJackson,
	CasperAkkerman,
	JensonButton = 109,
	DavidCoulthard,
	NicoRosberg,
	OscarPiastri,
	LiamLawson,
	JuriVips,
	TheoPourchaire,
	RichardVerschoor,
	LirimZendeli,
	DavidBeckmann,
	AlessioDeledda = 121,
	BentViscaal,
	EnzoFittipaldi,
	MarkWebber = 125,
	JacquesVilleneuve
};